#!/bin/bash
# Script 4: File Checker

echo "===== FILE CHECKER ====="

read -p "Enter file name: " FILE

if [ -f "$FILE" ]; then
    echo "File exists"

    echo "Size: $(du -h "$FILE" | cut -f1)"
    echo "Lines: $(wc -l < "$FILE")"

    echo "Preview:"
    head -5 "$FILE"
else
    echo "File not found"
fi
